### ISSUE TITLE
Invalid parameter number: number of bound variables does not match number of tokens

### ISSUE THREAD

**Issue by arnoldbird** [phanbook/phanbook#215]
I am getting a white screen.  In the error I log I see...

```
[Sun Dec 25 21:03:59.604668 2016] [:error] [pid 3177] [client 127.0.0.1:50798] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens' in /var/www/tembo/core/common/library/Auth/Auth.php:186

Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->query('SELECT `remembe...', Array, Array)
#3 [internal function]: Phalcon\\Mvc\\Model\\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()
#5 /var/www/tembo/core/common/library/Auth/Auth.php(186): Phalcon\\Mvc\\Model::findFirst(Array)
#6 /var/www/tembo/core/modules/frontend/controllers/ControllerBase.php(68): Phanbook\\Auth\\Auth->loginWithRememberMe()
#7 [internal function]: Phanbook\\Frontend\\Controllers\\ControllerBase->beforeExecuteRoute(Object(Phanbook\\Common\\Library\\Mvc\\Dispatcher))
#8 [internal function]: Phalcon\\Dispatcher->_dispatch()
#9 [internal funct in /var/www/tembo/core/common/library/Auth/Auth.php on line 186
```

**Comment by arnoldbird** [comment]
I restarted apache and rolled back the database.  Not sure which of those actions fixed it, but the site is working again.

**Comment by arnoldbird** [comment]
Happened again, out of nowhere:
```
[Sun Dec 25 22:18:06.293835 2016] [:error] [pid 5257] [client 127.0.0.1:52772] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens' in /var/www/tembo/core/common/library/Auth/Auth.php:186

Stack trace:
#0 [internal function]: PDOStatement->execute()
#1 [internal function]: Phalcon\\Db\\Adapter\\Pdo->executePrepared(Object(PDOStatement), Array, Array)
#2 [internal function]: Phalcon\\Db\\Adapter\\Pdo->query('SELECT `remembe...', Array, Array)
#3 [internal function]: Phalcon\\Mvc\\Model\\Query->_executeSelect(Array, Array, Array)
#4 [internal function]: Phalcon\\Mvc\\Model\\Query->execute()
#5 /var/www/tembo/core/common/library/Auth/Auth.php(186): Phalcon\\Mvc\\Model::findFirst(Array)
#6 /var/www/tembo/core/modules/frontend/controllers/ControllerBase.php(68): Phanbook\\Auth\\Auth->loginWithRememberMe()
#7 [internal function]: Phanbook\\Frontend\\Controllers\\ControllerBase->beforeExecuteRoute(Object(Phanbook\\Common\\Library\\Mvc\\Dispatcher))
#8 [internal function]: Phalcon\\Dispatcher->_dispatch()
#9 [internal funct in /var/www/tembo/core/common/library/Auth/Auth.php on line 186
```

The only way to recover the site seems to be to roll back the database.  Restarting appache doesn't fix it.

**Comment by arnoldbird** [comment]
I rolled back the database, reset my code to a previous version, restarted apache, and restarted my browser.  That got the site working again.

**Comment by arnoldbird** [comment]
It happened again and this time clearing my browser history fixed it.

**Comment by duythien** [comment]
What is your browser it work fine on my firefox

**Comment by arnoldbird** [comment]
I've seen it happen in Firefox and Chrome.  I use Firefox, but when the problem happens, I check in Chrome and I see it happen there too.

**Comment by arnoldbird** [comment]
I realized I was missing some things higher up in the log.  I didn't scroll up.  I just booted up my computer and went to my dev site, and I got a white screen and the same error I pasted above.  But here is some context from the log, higher up...

```
[Mon Dec 26 01:39:03.409228 2016] [mpm_prefork:notice] [pid 1211] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/phalcon.so' - /usr/lib/php/20131226/phalcon.so: undefined symbol: php_pdo_get_dbh_ce in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/php_fileinfo.so' - /usr/lib/php/20131226/php_fileinfo.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/php_openssl.so' - /usr/lib/php/20131226/php_openssl.so: cannot open shared object file: No such file or directory in Unknown on line 0
[Mon Dec 26 01:39:03.458836 2016] [mpm_prefork:notice] [pid 1211] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Mon Dec 26 01:39:03.458852 2016] [core:notice] [pid 1211] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 26 01:39:58.513874 2016] [:error] [pid 2321] [client 127.0.0.1:47736] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY093]: Invalid parameter number: number of bound
```

The ServerName thing I can fix.

**Comment by sergeyklay** [comment]
@arnoldbird

You have to install

* `php_fileinfo.so` - http://php.net/manual/en/book.fileinfo.php
* `php_openssl.so` - http://php.net/manual/en/book.openssl.php

And 

> undefined symbol: `php_pdo_get_dbh_ce` 

You need to load PDO first before Phalcon.
In your computer, have a look at the `/etc/php5/apache2filter/conf.d/` folder (_or any other directory containing Apache configs_)

The ini file that loads phalcon should be prefixed to a number higher than the one PDO is. So in my system I have:

`20-pdo_mysql.ini` `50-phalcon.ini`


-----------------

@duythien How about adding this to the install manual?

**Comment by arnoldbird** [comment]
sergeyklay,

According to phpinfo(), all of those things are enabled.  And the phalcon ini does have a higher number already.  I still have a white screen.

Also, keep in mind that phanbook has worked ok much of the time.  This is an intermittent problem.  So initially, I don't see how it could be server config.

Thank you.

**Comment by duythien** [comment]
@sergeyklay Yes. Maybe we need to note that for install manual
