### ISSUE TITLE
Problem of Google OAuth

### ISSUE THREAD

**Issue by mzch** [phanbook/phanbook#264]
Hi,

I set up Google OAuth and Analytics API, but PhanBook failed to login/sign up using Google OAuth.
Could you tell me how to fix this issue?

- Log
```
[Fri Nov 01 22:08:29.166115 2019] [proxy_fcgi:error] [pid 29764:tid 139764724483840] [client 203.141.134.112:58156] AH01071: Got error 'PHP message: PHP Notice:  Undefined property: Phalcon\\Config::$google in /srv/phanbook/core/modules/oauth/controllers/LoginController.php on line 72PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Phanbook\\Google\\Auth::__construct() must be an instance of Phalcon\\Config, null given, called in /srv/phanbook/core/modules/oauth/controllers/LoginController.php on line 72 and defined in /srv/phanbook/core/common/library/Google/Auth.php:39\nStack trace:\n#0 /srv/phanbook/core/modules/oauth/controllers/LoginController.php(72): Phanbook\\Google\\Auth->__construct(NULL)\n#1 [internal function]: Phanbook\\Oauth\\Controllers\\LoginController->googleAction()\n#2 [internal function]: Phalcon\\Dispatcher->callActionMethod(Object(Phanbook\\Oauth\\Controllers\\LoginController), 'googleAction', Array)\n#3 [internal function]: Phalcon\\Dispatcher->dispatch()\n#4 /srv/phanbook/core/common/Application.php(158): Phalcon\\Mvc\\Application->handle()\n#5 /srv/phanbook/core/common/Application.php(108): Phanbook\\Common\\Application->getOutput()\n#6 /srv/phanbook/public/index.php(23): Phanbook\\Common\\Application->run()\n#7 {main}\n  thrown in /srv/phanbook/core/common/...', referer: https://stack.uixis.org/users/signin
```

**Comment by duythien** [comment]
@mzch Have add config google to file .env ?

**Comment by mzch** [comment]
Yes, they are `ANALYTIC_CLIENT_ID=` and `ANALYTIC_SECRET=`, aren't they?

**Comment by duythien** [comment]
Yes

**Comment by duythien** [comment]
@mzch See here https://github.com/phanbook/phanbook/pull/265
