### ISSUE TITLE
Question views are not working

### ISSUE THREAD

**Issue by rmrio** [phanbook/phanbook#52]
Hi, i have a problem with urls like /questions/*, the error is:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Phalcon\Mvc\Model::validate() must implement   interface Phalcon\ValidationInterface, instance of Phalcon\Mvc\Model\Validator\Uniqueness given in     /usr/share/nginx/html/phanbook/core/common/models/Users.php:856 Stack trace: #0   /usr/share/nginx/html/phanbook/core/common/models/Users.php(856): Phalcon\Mvc\Model-   >validate(Object(Phalcon\Mvc\Model\Validator\Uniqueness)) #1 [internal function]: Phanbook\Models\Users-   >validation() #2 [internal function]: Phalcon\Mvc\Model->fireEventCancel('validation') #3 [internal function]:    Phalcon\Mvc\Model->_preSave(Object(Phalcon\Mvc\Model\MetaData\Memory), true, 'id') #4 [internal    function]: Phalcon\Mvc\Model->save() #5 [internal function]: Phalcon\Mvc\Model-   >_preSaveRelatedRecords(Object(Phalcon\Db\Adapter\Pdo\Mysql), Array) #6    /usr/share/nginx/html/phanbook/core/modules/frontend/controllers/PostsController.php(379):    Phalcon\Mvc\Model->save() #7 [internal function]: Phanbook\Frontend\Controllers\PostsController-   >viewAction(52, 'a-tool-fo in /usr/share/nginx/html/phanbook/core/common/models/Users.php on line 856
```

My server is:
Ubuntu 16.04
php7
nginx

I follow these docs http://phanbook.com/docs/manual for installation.

Please help

**Comment by duythien** [comment]
Hello @rmrio 

Because the Phanbook use Phaclon to develop, so that right now Phalcon do not support PHP7 that mean Phanbook it will not woking

Try use PHP 5.6.x it will work fine

**Comment by rmrio** [comment]
Ok, i will try. It should be specified in the docs.
